//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.25 at 01:10:54 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hamsoft.com/soapdemo/gen", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hamsoft.soapclientdemo.schemas.country;
